// Generated by CoffeeScript 1.10.0
var React, style;

React = require("react");

style = {
  container: {
    overflow: "auto",
    position: "relative",
    flex: 1
  },
  inner: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0
  }
};

module.exports = React.createClass({
  displayName: "ScrollView",
  render: function() {
    return React.createElement("div", {
      "style": style.container
    }, React.createElement("div", {
      "style": style.inner
    }, this.props.children));
  }
});
