// Generated by CoffeeScript 1.10.0
var React;

React = require("react");

module.exports = React.createClass({
  displayName: "Button",
  mixins: [require('react-addons-pure-render-mixin')],
  render: function() {
    return React.createElement("div", Object.assign({
      "className": "btn btn-default"
    }, this.props));
  }
});
