// Generated by CoffeeScript 1.10.0
var React, Row;

React = require("react");

Row = require("./layout").Row;

module.exports = React.createClass({
  displayName: "Toolbar",
  render: function() {
    return React.createElement(Row, Object.assign({
      "className": "toolbar"
    }, this.props));
  }
});
