// Generated by CoffeeScript 1.10.0
module.exports = {
  Chat: require("./root/chat"),
  RoomPanel: require("./root/room-panel"),
  TopToolbar: require("./root/top-toolbar"),
  TransfersPanel: require("./root/transfers-panel"),
  UsersPanel: require("./root/users-panel")
};
