// Generated by CoffeeScript 1.10.0
var Column, Divider, Gutter, React, Row, Toolbar, UI, ref;

React = require("react");

UI = require("../../ui");

Toolbar = UI.Toolbar;

ref = UI.Layout, Row = ref.Row, Column = ref.Column, Divider = ref.Divider, Gutter = ref.Gutter;

module.exports = React.createClass({
  displayName: "TransfersPanel",
  render: function() {
    return React.createElement(Row, {
      "flex": 2.
    }, React.createElement(Column, null, React.createElement(Toolbar, null, "Downloads")), React.createElement(Divider, {
      "vertical": true
    }), React.createElement(Column, null, React.createElement(Toolbar, null, "Uploads")));
  }
});
