// Generated by CoffeeScript 1.10.0
let Column

let Divider
let Gutter
let List
let ListItem
let Row
let ref
let ref1

import React from "react"
import UI from "../../ui"
const Toolbar = UI.Toolbar

ref = UI.Layout, Row = ref.Row, Column = ref.Column, Divider = ref.Divider, Gutter = ref.Gutter

ref1 = UI.List, List = ref1.List, ListItem = ref1.ListItem

const ScrollView = UI.View.ScrollView
const Button = UI.Buttons.Button

export default class extends React.Component {
  static displayName = "UsersPanel"

  render() {
    return <Column><Toolbar><Row alignItems="center"><Column><span>Users ({this.props.users.count()})</span></Column><Button><i className="fa fa-plus" /></Button></Row></Toolbar><ScrollView><List>{this.props.users.sort().map(user => <ListItem key={user}>{user}</ListItem>)}</List></ScrollView></Column>
  }
}
