// Generated by CoffeeScript 1.10.0
var Column, Divider, Gutter, List, ListItem, Row, ref, ref1;

var React = require("react");
var UI = require("../../ui");
var Toolbar = UI.Toolbar;

ref = UI.Layout, Row = ref.Row, Column = ref.Column, Divider = ref.Divider, Gutter = ref.Gutter;

ref1 = UI.List, List = ref1.List, ListItem = ref1.ListItem;

var ScrollView = UI.View.ScrollView;
var Button = UI.Buttons.Button;

module.exports = React.createClass({
  displayName: "UsersPanel",
  render: function() {
    return React.createElement(Column, null, React.createElement(Toolbar, null, React.createElement(Row, {
      "alignItems": "center"
    }, React.createElement(Column, null, React.createElement("span", null, "Users (", this.props.users.count(), ")")), React.createElement(Button, null, React.createElement("i", {
      "className": "fa fa-plus"
    })))), React.createElement(ScrollView, null, React.createElement(List, null, this.props.users.sort().map(function(user) {
      return React.createElement(ListItem, {
        "key": user
      }, user);
    }))));
  }
});
